### ISSUE TITLE
Extension doesn't work with QS September2020

### ISSUE THREAD

**Issue by nixnut** [eCraftExtensions/ecraft-kpi#4]
After upgrading to the September 2020 reload of Qlik Sense this extension stopped working.

I get these errors in the console of the browser:
Uncaught SyntaxError: Unexpected token '<'
Uncaught SyntaxError: Unexpected token '<'

After trying to set some properties I get more errors:

setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
$apply @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
l @ analysis.96debf42e3d16d6306b5.js:9
(anonymous) @ analysis.96debf42e3d16d6306b5.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
$apply @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ qvangular.21964f16a5ee138df65b.js:9
dispatch @ jquery.a34e6c8099a68507375c.js:9
v.handle @ jquery.a34e6c8099a68507375c.js:9
trigger @ jquery.a34e6c8099a68507375c.js:9
(anonymous) @ jquery.a34e6c8099a68507375c.js:9
each @ jquery.a34e6c8099a68507375c.js:9
each @ jquery.a34e6c8099a68507375c.js:9
trigger @ jquery.a34e6c8099a68507375c.js:9
e @ setup-view.bf2af246af27462c071d.js:9
Z9ZH.t.Gesture.augment.end @ touchejs.83ef956f1bfa8a418eac.js:9
(anonymous) @ touchejs.83ef956f1bfa8a418eac.js:9
Z9ZH.t.GestureHandler.t.FlowHandler.augment.trigger @ touchejs.83ef956f1bfa8a418eac.js:9
Z9ZH.t.GestureHandler.t.FlowHandler.augment.end @ touchejs.83ef956f1bfa8a418eac.js:9
(anonymous) @ touchejs.83ef956f1bfa8a418eac.js:9
Z9ZH.t.SuperHandler.t.FlowHandler.augment.onEnd @ touchejs.83ef956f1bfa8a418eac.js:9
Z9ZH.t.FlowHandler.Object.augment.handleEvent @ touchejs.83ef956f1bfa8a418eac.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$broadcast @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ analysis.96debf42e3d16d6306b5.js:9
c @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$broadcast @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ analysis.96debf42e3d16d6306b5.js:9
c @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
angular.ee939c2f9e797b5055f7.js:9 TypeError: getSheets is not a function
    at options (ecraft-kpi.js:126)
    at u (setup-view.bf2af246af27462c071d.js:9)
    at Object.e [as fillOptions] (setup-view.bf2af246af27462c071d.js:9)
    at s (103.f49577e6ee4e6bd5e326.js:9)
    at new o.controller (103.f49577e6ee4e6bd5e326.js:9)
    at Object.h [as instantiate] (angular.ee939c2f9e797b5055f7.js:9)
    at r (angular.ee939c2f9e797b5055f7.js:9)
    at qvangular.21964f16a5ee138df65b.js:9
    at h.$digest (angular.ee939c2f9e797b5055f7.js:9)
    at angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$broadcast @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ analysis.96debf42e3d16d6306b5.js:9
c @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$broadcast @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ analysis.96debf42e3d16d6306b5.js:9
c @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
setup-view.bf2af246af27462c071d.js:9 Error! No component found with name "pp-ec-about"
a @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
s @ 103.f49577e6ee4e6bd5e326.js:9
(anonymous) @ 103.f49577e6ee4e6bd5e326.js:9
$digest @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
o @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
setTimeout (async)
Wn.a.defer @ angular.ee939c2f9e797b5055f7.js:9
$evalAsync @ angular.ee939c2f9e797b5055f7.js:9
(anonymous) @ angular.ee939c2f9e797b5055f7.js:9
h @ angular.ee939c2f9e797b5055f7.js:9
then @ angular.ee939c2f9e797b5055f7.js:9
g @ setup-view.bf2af246af27462c071d.js:9
(anonymous) @ setup-view.bf2af246af27462c071d.js:9
a.emit @ enigma.78fea08e5ef0fe3cffb8.js:9
e @ enigma.78fea08e5ef0fe3cffb8.js:9
angular.ee939c2f9e797b5055f7.js:9 TypeError: getSheets is not a function
    at options (ecraft-kpi.js:126)
    at u (setup-view.bf2af246af27462c071d.js:9)
    at Object.e [as fillOptions] (setup-view.bf2af246af27462c071d.js:9)
    at s (103.f49577e6ee4e6bd5e326.js:9)
    at new o.controller (103.f49577e6ee4e6bd5e326.js:9)
    at Object.h [as instantiate] (angular.ee939c2f9e797b5055f7.js:9)
    at r (angular.ee939c2f9e797b5055f7.js:9)
    at qvangular.21964f16a5ee138df65b.js:9
    at h.$digest (angular.ee939c2f9e797b5055f7.js:9)
    at angular.ee939c2f9e797b5055f7.js:9

**Comment by lehtomar** [comment]
Fixed in latest commit
